const actions = {
  //User
  FETCH_USER: "FETCH_USER",
  //
  OPEN_LEAGUE_INFO: "OPEN_LEAGUE_INFO",
  ADD_LEAGUE: "ADD_LEAGUE",
  //League Actions
  LEAGUE_ADD_FETCH_ID: "LEAGUE_ADD_FETCH_ID",
  LEAGUE_FETCH_LEAGUE: "LEAGUE_FETCH_LEAGUE",
  //League Table Actions
  LEAGUE_TABLE_SET_ROUND: "LEAGUE_TABLE_SET_ROUND",
  LEAGUE_TABLE_NEXT_ROUND: "LEAGUE_TABLE_NEXT_ROUND",
  LEAGUE_TABLE_PREV_ROUND: "LEAGUE_TABLE_PREV_ROUND",
  //Leagues Table actions
  LEAGUES_TABLE_FETCH_ALL: "LEAGUES_TABLE_FETCH_ALL",
  LEAGUES_TABLE_PROMPT_JOIN_LEAGUE: "LEAGUES_TABLE_PROMPT_JOIN_LEAGUE",
  LEAGUES_TABLE_FETCH_MY_LEAGUES: "LEAGUES_TABLE_FETCH_MY_LEAGUES",
  //Round Table actions
  ROUND_TABLE_SET_ROUND: "ROUND_TABLE_SET_ROUND",
  ROUND_TABLE_NEXT_ROUND: "ROUND_TABLE_NEXT_ROUND",
  ROUND_TABLE_PREV_ROUND: "ROUND_TABLE_PREV_ROUND",
  //Guess table action
  GUESS_TABLE_SET_ROUND: "GUESS_TABLE_SET_ROUND",
  GUESS_TABLE_NEXT_ROUND: "GUESS_TABLE_NEXT_ROUND",
  GUESS_TABLE_PREV_ROUND: "GUESS_TABLE_PREV_ROUND",
  GUESS_TABLE_SET_ROUNDS: "GUESS_TABLE_SET_ROUNDS",
  GUESS_TABLE_EDIT_ROUND: "GUESS_TABLE_EDIT_ROUND",
  GUESS_TABLE_SAVE_ROUND_GUESSES: "GUESS_TABLE_SAVE_ROUND_GUESSES",
  GUESS_TABLE_SET_MATCH_GUESS: "GUESS_TABLE_SET_MATCH_GUESS",
  GUESS_TABLE_PREVIEW_ROUND: "GUESS_TABLE_PREVIEW_ROUND",
  //admin
  ADMIN_CREATE_NEW_CHAMPIONSHIP: "ADMIN_CREATE_NEW_CHAMPIONSHIP"
}

export default actions;
