const actions = {
  //User
  FETCH_USER: "FETCH_USER",
  //
  OPEN_LEAGUE_INFO: "OPEN_LEAGUE_INFO",
  ADD_LEAGUE: "ADD_LEAGUE",
  //League Table Actions
  LEAGUE_TABLE_SET_ROUND: "LEAGUE_TABLE_SET_ROUND",
  LEAGUE_TABLE_NEXT_ROUND: "LEAGUE_TABLE_NEXT_ROUND",
  LEAGUE_TABLE_PREV_ROUND: "LEAGUE_TABLE_PREV_ROUND",
  //Round Table actions
  ROUND_TABLE_SET_ROUND: "ROUND_TABLE_SET_ROUND",
  ROUND_TABLE_NEXT_ROUND: "ROUND_TABLE_NEXT_ROUND",
  ROUND_TABLE_PREV_ROUND: "ROUND_TABLE_PREV_ROUND",
  //Guess table action
  GUESS_TABLE_SET_ROUND: "GUESS_TABLE_SET_ROUND",
  GUESS_TABLE_NEXT_ROUND: "GUESS_TABLE_NEXT_ROUND",
  GUESS_TABLE_PREV_ROUND: "GUESS_TABLE_PREV_ROUND",
  //admin
  ADMIN_CREATE_NEW_CHAMPIONSHIP: "ADMIN_CREATE_NEW_CHAMPIONSHIP"
}

export default actions;
